packages:
  - .
  - src/ckeditor

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - cypress
  - esbuild
  - nice-napi
  - protobufjs

overrides:
  'ajv@^8': '^8.18.0'
  'brace-expansion@^1': '^1.1.13'
  'brace-expansion@^2': '^2.0.3'
  'brace-expansion@^5': '^5.0.5'
  'diff@^7': '^8.0.3'
  'fast-xml-parser': '^5.5.7'
  'flatted': '^3.4.2'
  'lodash': '^4.18.0'
  'node-forge': '^1.4.0'
  'path-to-regexp@^0.1': '0.1.13'
  'picomatch@^2': '^2.3.2'
  'picomatch@^4': '^4.0.4'
  'qs@^6': '^6.14.2'
  'serialize-javascript@^6': '^7.0.5'
  'serialize-javascript@^7': '^7.0.5'
  'socket.io-parser': '^4.2.6'
  'yaml@^1': '1.10.3'
  'yaml@^2': '^2.8.3'
  'tar@^6': '^7.5.11'
  'vite': '^6.4.2'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'vite'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
