onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - cypress
  - esbuild
  - nice-napi
  - protobufjs

overrides:
  tmp: ^0.2.5
  form-data: ^4.0.4
  'vite@^4.0.0': ^5.4.21
  webpack-dev-middleware: 5.3.4
  esbuild: ^0.25.0
  '@babel/runtime@7': ^7.26.10
  'webpack-dev-server': ^5.2.1
  'tar@7.5.1': ^7.5.2

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
