packages:
  - .
  - src/ckeditor

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - cypress
  - esbuild
  - nice-napi
  - protobufjs

overrides:
  'diff@^7': '^8.0.3'
  'serialize-javascript@^6': '^7.0.5'
  'tar@^6': '^7.5.11'
  'webpack-dev-server@^5': '^5.2.4'
  'ws@^8': '^8.20.1'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'axios'
  - 'vite'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  cypress: true
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  protobufjs: true
  snyk: false
