onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - cypress
  - esbuild
  - nice-napi
  - protobufjs

overrides:
  qs@<6.14.1: '^6.14.1'
  tar@^6.0.0: ^7.5.4
  diff@^7.0.0: '^8.0.3'
  diff@^8.0.0: '^8.0.3'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
