packages:
  - .
  - src/ckeditor

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - cypress
  - esbuild
  - nice-napi
  - protobufjs

overrides:
  'ajv@^8': '^8.18.0'
  'diff@^7': '^8.0.3'
  'qs@^6': '^6.14.2'
  'serialize-javascript@^6': '^7.0.3'
  'tar@^6': '^7.5.11'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
